[build]
  base = "genius-crm-deploy"
  command = "npm run build"
  publish = "genius-crm-deploy/dist"
  functions = "genius-crm-deploy/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
